'use strict';

app.config(function($stateProvider,$urlRouterProvider,$httpProvider,APP){

     $urlRouterProvider.otherwise('/');

        $stateProvider
            .state('main',{
                url:"/",
                templateUrl:APP.VIEWS+'/main/index.html',
                controller:"MainController"
            })
            .state('contatoinform',{
                url:"/contatoinform",
                templateUrl:APP.VIEWS+'/contato/informatica.html',
                controller:"MainController"
            })
            .state('contatocorreg',{
                url:"/contatocorreg",
                templateUrl:APP.VIEWS+'/contato/corregedoria.html',
                controller:"MainController"
            })            
            .state('audiencia',{
                url:"/audiencia",
                templateUrl:APP.VIEWS+'/audiencia/index.html',
                controller:"AudienciaCtrl"
            })
            .state('audiencialista',{
                url:"/audiencia/lista",
                templateUrl:APP.VIEWS+'/audiencia/lista.html',
                controller:"AudienciaListaController"
            })
            .state('agenda',{
                url:"/agenda",
                templateUrl:APP.VIEWS+'/agenda/index.html',
                controller:"AgendaCtrl"
            })
            .state('audienciaItem',{
                url:"/audiencia/item",
                templateUrl:APP.VIEWS+'/audiencia/item.html',
                controller:"AudienciaItemController"
            })
            .state('tutela',{
                url:"/tutela",
                templateUrl:APP.VIEWS+'/tutelacoletiva/index.html',
                controller:"TutelaCtrl"
            })
            .state('tutelalista',{
                url:"/tutela/lista",
                templateUrl:APP.VIEWS+'/tutelacoletiva/lista.html',
                controller:"TutelaListaController"
            })
            .state('tutelaItem',{
                url:"/tutela/item",
                templateUrl:APP.VIEWS+'/tutelacoletiva/item.html',
                controller:"TutelaItemController"
            })
            .state('sessoes',{
                url:"/sessoes",
                templateUrl:APP.VIEWS+'/sessoes/index.html',
                controller:"SessoesCtrl"
            })
            .state('sessaoItem',{
                url:"/sessao",
                templateUrl:APP.VIEWS+'/sessoes/item.html',
                controller:"SessaoItemCtrl"
            })

            .state('peticao',{
                url:"/peticao",
                templateUrl:APP.VIEWS+'/peticao/index.html',
                controller:"PeticaoCtrl"
            })
            .state('peticaolista',{
                url:"/peticao/lista",
                templateUrl:APP.VIEWS+'/peticao/lista.html',
                controller:"PeticaoListaController"
            })           
            .state('peticaoItem',{
                url:"/peticao/item",
                templateUrl:APP.VIEWS+'/peticao/item.html',
                controller:"PeticaoItemController"
            })
            .state('docsdiversos',{
                url:"/docsdiversos",
                templateUrl:APP.VIEWS+'/docsdiversos/index.html',
                controller:"DocsdiversosCtrl"
            })
            .state('docsdiversoslista',{
                url:"/docsdiversos/lista",
                templateUrl:APP.VIEWS+'/docsdiversos/lista.html',
                controller:"DocsdiversosListaController"
            })
           
            .state('docsdiversosItem',{
                url:"/docsdiversos/item",
                templateUrl:APP.VIEWS+'/docsdiversos/item.html',
                controller:"DocsdiversosItemController"
            })
            .state('flagrante',{
                url:"/flagrante",
                templateUrl:APP.VIEWS+'/flagrante/index.html',
                controller:"FlagranteCtrl"
            })
            .state('flagrantelista',{
                url:"/flagrante/lista",
                templateUrl:APP.VIEWS+'/flagrante/lista.html',
                controller:"FlagranteListaController"
            })           
            .state('flagranteItem',{
                url:"/flagrante/item",
                templateUrl:APP.VIEWS+'/flagrante/item.html',
                controller:"FlagranteItemController"
            })
            .state('acordoemediacao',{
                url:"/acordoemediacao",
                templateUrl:APP.VIEWS+'/acordoemediacao/index.html',
                controller:"AcordoemediacaoCtrl"
            })
            .state('acordoemediacaolista',{
                url:"/acordoemediacao/lista",
                templateUrl:APP.VIEWS+'/acordoemediacao/lista.html',
                controller:"AcordoemediacaoListaController"
            })           
            .state('acordoemediacaoItem',{
                url:"/acordoemediacao/item",
                templateUrl:APP.VIEWS+'/acordoemediacao/item.html',
                controller:"AcordoemediacaoItemController"
            })
            .state('historico',{
                url:"/historico",
                templateUrl:APP.VIEWS+'/historico/index.html',
                controller:"HistoricoCtrl"
            })            
            .state('historicolista',{
                url:"/historico/lista",
                templateUrl:APP.VIEWS+'/historico/lista.html',
                controller:"HistoricoListaController"
            })
            .state('historicoItem',{
                url:"/historico/item",
                templateUrl:APP.VIEWS+'/historico/item.html',
                controller:"HistoricoItemController"
            })
            .state('dadosassistiso',{
                url:"/dadosassistido",
                templateUrl:APP.VIEWS+'/dadosassistido/index.html',
                controller:"DadosassistidoCtrl"
            })
            .state('dadosassistidolista',{
                url:"/dadosassistido/lista",
                templateUrl:APP.VIEWS+'/dadosassistido/lista.html',
                controller:"DadosassistidoListaController"
            })
            .state('dadosassistidoItem',{
                url:"/dadosassistido/item",
                templateUrl:APP.VIEWS+'/dadosassistido/item.html',
                controller:"DadosassistidoItemController"
            })
            .state('juri',{
                url:"/juri",
                templateUrl:APP.VIEWS+'/juri/index.html',
                controller:"JuriCtrl"
            })
            .state('jurilista',{
                url:"/juri/lista",
                templateUrl:APP.VIEWS+'/juri/lista.html',
                controller:"JuriListaController"
            })
            .state('juriItem',{
                url:"/juri/item",
                templateUrl:APP.VIEWS+'/juri/item.html',
                controller:"JuriItemController"
            })
            .state('intimacao',{
                url:"/intimacao",
                templateUrl:APP.VIEWS+'/intimacao/index.html',
                controller:"IntimacaoCtrl"
            })
            .state('intimacaolista',{
                url:"/intimacao/lista",
                templateUrl:APP.VIEWS+'/intimacao/lista.html',
                controller:"IntimacaoListaController"
            })
            .state('intimacaoItem',{
                url:"/intimacao/item",
                templateUrl:APP.VIEWS+'/intimacao/item.html',
                controller:"IntimacaoItemController"
            })
            .state('atividadesexternas',{
                url:"/atividadesexternas",
                templateUrl:APP.VIEWS+'/atividadesexternas/index.html',
                controller:"AtividadesCtrl"
            })
            .state('configuracaoeditar',{
                url:"/configuracao/index",
                templateUrl:APP.VIEWS+'/configuracao/index.html',
                controller:"ConfigController"
            })

})
